version:  '3.9'

services:
  db:
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - "postgres-db-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: despachalo_dev
      POSTGRES_USER: despachalo_dev
      POSTGRES_PASSWORD: despachalo_dev

volumes:
  postgres-db-data:
